#!/bin/bash

echo "Configuring production retention policies ..."
INFLUXDB_INIT_PORT="${INFLUXDB_INIT_PORT:-8086}"
INFLUX_DATABASES="${INFLUX_DATABASE:-telegraf logs metrics}"
INFLUX_DATABASE_RETENTION="${INFLUX_DATABASE_RETENTION:-7d}"
INFLUX_DATABASE_REPLICATION="${INFLUX_DATABASE_REPLICATION:-1}"
INFLUX_DATABASE_SHARD_DURATION="${INFLUX_DATABASE_SHARD_DURATION:-1h}"
INTERNAL_INFLUX_DATABASE="_internal"
INTERNAL_INFLUX_DATABASE_RETENTION="${INTERNAL_INFLUX_DATABASE_RETENTION:-1d}"
INTERNAL_INFLUX_DATABASE_REPLICATION="${INTERNAL_INFLUX_DATABASE_REPLICATION:-1}"
INTERNAL_INFLUX_DATABASE_SHARD_DURATION="${INTERNAL_INFLUX_DATABASE_SHARD_DURATION:-1h}"

if [ -n "${INFLUXDB_ADMIN_USER}" ] && [ -n "${INFLUXDB_ADMIN_PASSWORD}" ]; then
    INFLUX_CMD="influx -host 127.0.0.1 -port $INFLUXDB_INIT_PORT -username ${INFLUXDB_ADMIN_USER} -password ${INFLUXDB_ADMIN_PASSWORD} -execute "
else
    INFLUX_CMD="influx -host 127.0.0.1 -port $INFLUXDB_INIT_PORT -execute "
fi

for influx_db in $INFLUX_DATABASES; do
    echo "Create DB: \"$influx_db\""
    $INFLUX_CMD "CREATE DATABASE \"$influx_db\""
    $INFLUX_CMD "ALTER RETENTION POLICY \"autogen\" ON \"$influx_db\" DURATION $INFLUX_DATABASE_RETENTION REPLICATION $INFLUX_DATABASE_REPLICATION SHARD DURATION $INFLUX_DATABASE_SHARD_DURATION DEFAULT"
done

echo "Create DB: \"$INTERNAL_INFLUX_DATABASE\""
$INFLUX_CMD "CREATE DATABASE \"$INTERNAL_INFLUX_DATABASE\""
$INFLUX_CMD "ALTER RETENTION POLICY \"autogen\" ON \"$INTERNAL_INFLUX_DATABASE\" DURATION $INTERNAL_INFLUX_DATABASE_RETENTION REPLICATION $INTERNAL_INFLUX_DATABASE_REPLICATION SHARD DURATION $INTERNAL_INFLUX_DATABASE_SHARD_DURATION DEFAULT"

echo "Configuring production retention policies: DONE"